spring:
  application:
    name: msa-weather-eureka-client-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.18:8761/eureka/
zuul:
  routes:
    city:
      path: /city/**
      serviceId: weather-city-eureka
    data:
      path: /data/**
      serviceId: weather-data-eureka
server:
  port: 8085
