
# 热部署静态文件
spring:
  thymeleaf:
    cache: false
  application:
    name: weather-report-eureka-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8084


feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000