

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: weather-eureka-client-feign

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

