

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.18:8761/eureka/
spring:
  application:
    name: weather-eureka-client-feign-hystrix

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

