spring:
  redis:
    host: 192.168.1.18
    port: 6379
  application:
    name: weather-collection-eureka-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.18:8761/eureka/
server:
  port: 8081

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000