spring:
  redis:
    host: 192.168.1.18
    port: 6379
  application:
    name: weather-collection-eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
