spring:
  application:
    name: weather-eureka-client-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    hi:
      path: /hi/**
      serviceId: weather-eureka-client



