
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.18:8761/eureka/
spring:
  application:
    name: weather-data-eureka
  redis:
    host: 192.168.1.18
    port: 6379
server:
  port: 8082